### PR TITLE
embedded editor

### PR DESCRIPTION
**Pull request by micuat**
as discussed for cosa grant - work in progress!

- [x] use docs folder instead of gh-pages branch
- [x] add CM6
- [x] drop `prism` and use non-editable CM instance for "usage" one liner
- [x] add hash routing (e.g., `/#voronoi`)
- [x] refactoring
- [ ] cover all the functions
- [x] short instructions for using editor / running code
- [x] highlight or indication when code is executed
- [x] button for running code
- [x] button for reset code / open in editor / error console
  - this might require refactoring 
- [ ] optional: prettier highlighting
- [x] internationalization

### CODE REVIEW

**Comment by ojack** [comment]
This is so amazing already!!!

Eventually would like to add (does not have to be in this PR but just noting here):
- short instructions for using editor / running code
- highlight or indication when code is executed
- button for running code

**Comment by micuat** [comment]
I left out some points - contents and internationalization - but I guess the listed functionalities are implemented. Don't forget to change the gh-pages settings (use `docs/` instead of `gh-pages` branch) when you merge!

**Comment by micuat** [comment]
something missing is a button to go back to top - although it's not essential (in terms of usability). and I don't know how to retrieve the "root" path (like in this https://naotohieda.com/hydra-functions case) within choo

**Comment by micuat** [comment]
I added i18next - it looks good but we need to

* make a documentation on "how to contribute"
* think about how to translate comments on the code - maybe a better way would be to move the comments separate from the code and show them somewhere else outside the editor.

**Comment by ojack** [comment]
hii, is this ready to merge?

**Comment by micuat** [comment]
Actually I was really confused earlier that there's this repository (under your account) and one on hydra-synth. I lost track of this branch :(

**Comment by micuat** [comment]
I just reviewed both repositories, and I think these changes are already merged into hydra-synth/hydra-functions. So I'm closing this PR. I suggest you archive this repository as it is already moved to hydra-synth. (But I have a PR on hydra-synth/hydra-functions that I want you to review)

**Pull request closed without merging**
